cmkbeat:
  period: 30s
  cmkHost: "192.168.0.19:6557"

name: livestatus

output.elasticsearch:
  enabled: true
  hosts: ["localhost:9200"]
  index: "livestatus-%{+yyyy.MM.dd}"
  template.enabled: true
  template.name: "livestatus"
  template.path: "${path.config}/cmkbeat.template.json"
  template.overwrite: true
  template.versions.2x.enabled: false

output.logstash:
  enabled: false
  hosts: ["localhost:5044"]
  timeout: 30
  max_retries: 0
  index: 'livestatus'

output.kafka:
  enabled: false

output.redis:
  enabled: false

output.file:
  enabled: false

output.console:
  enabled: false

path:
  home: /usr/share/cmkbeat
  config: /etc/cmkbeat
  data: /var/lib/cmkbeat
  logs: /var/log/cmkbeat

logging:
  level: info
  to_syslog: false
  metrics.enabled: false
  to_files: true
  files:
    path: /var/log/cmkbeat
    name: cmkbeat
    rotateeverybytes: 10485760
    keepfiles: 4  

#================================ General =====================================

# The name of the shipper that publishes the network data. It can be used to group
# all the transactions sent by a single shipper in the web interface.
#name:

# The tags of the shipper are included in their own field with each
# transaction published.
#tags: ["service-X", "web-tier"]

# Optional fields that you can specify to add additional information to the
# output.
#fields:
#  env: staging

#================================ Outputs =====================================

# Configure what outputs to use when sending the data collected by the beat.
# Multiple outputs may be used.

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["localhost:9200"]

  # Optional protocol and basic auth credentials.
  #protocol: "https"
  #username: "elastic"
  #password: "changeme"

#----------------------------- Logstash output --------------------------------
#output.logstash:
  # The Logstash hosts
  #hosts: ["localhost:5044"]

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"

#================================ Logging =====================================

# Sets log level. The default log level is info.
# Available log levels are: critical, error, warning, info, debug
#logging.level: debug

# At debug level, you can selectively enable logging only for some components.
# To enable all selectors use ["*"]. Examples of other selectors are "beat",
# "publish", "service".
#logging.selectors: ["*"]
